version: '3'
services:
  myvpn:
    build: .
    expose:
      - "8888"
    devices:
      - "/dev/net/tun"
    cap_add:
      - NET_ADMIN
    networks:
      - divid_net

networks:
  divid_net:
    external: true
    name: divid-net # attach to swarm network
